# Generated by Django 3.2.8 on 2023-11-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='salud',
            field=models.IntegerField(default=0),
        ),
    ]
