# Generated by Django 3.2.8 on 2023-11-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0002_auto_20231105_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasAtencionMedico',
            fields=[
                ('rut_medico', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fec_hr_ini', models.DateTimeField()),
                ('fec_hr_ter', models.DateTimeField()),
                ('nombre_medico', models.CharField(max_length=100)),
                ('apellido_medico', models.CharField(max_length=100)),
                ('especialidad', models.IntegerField()),
            ],
        ),
    ]
