# Generated by Django 3.2.8 on 2023-11-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0004_alter_horasatencionmedico_rut_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasatencionmedico',
            name='rut_dv_medico',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
