# Generated by Django 4.2.7 on 2023-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0006_remove_horasatencionmedico_fec_hr_ter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id_afp', models.IntegerField(primary_key=True, serialize=False)),
                ('afp', models.CharField(max_length=50)),
                ('descuento_afp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('ate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateField()),
                ('hr_atencion', models.CharField(max_length=5)),
                ('costo', models.IntegerField()),
                ('medico_med_run', models.IntegerField()),
                ('pac_run', models.IntegerField()),
                ('hora_id_hora', models.IntegerField()),
                ('centro_medico_id_centro_medico', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id_centro_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('centro_medico', models.CharField(max_length=50)),
                ('fono_centro', models.IntegerField()),
                ('direccion_id_direccion', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAtenMedicasMensuales',
            fields=[
                ('mes_anno_atencion', models.CharField(max_length=7)),
                ('atencion_ate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('paciente', models.CharField(max_length=100)),
                ('sistema_salud_paciente', models.CharField(max_length=100)),
                ('descrip_sistema_salud', models.CharField(max_length=100)),
                ('costo_atencion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna_id_comuna', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_empleado', models.IntegerField()),
                ('dv_empleado', models.CharField(max_length=1)),
                ('nom_empleado', models.CharField(max_length=20)),
                ('ap_empleado', models.CharField(max_length=20)),
                ('fecha_contrato', models.DateField()),
                ('telefono_empleado', models.IntegerField()),
                ('correo_empleado', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=20)),
                ('rol_id_rol', models.IntegerField()),
                ('sueldo_base', models.IntegerField()),
                ('contraseña_empleado', models.CharField(max_length=50)),
                ('prevision_salud_id_prevision', models.IntegerField()),
                ('afp_id_afp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ErroresProceso',
            fields=[
                ('id_error', models.IntegerField(primary_key=True, serialize=False)),
                ('subprograma_error', models.CharField(max_length=150)),
                ('descripcion_error', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('esp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id_hora', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_y_hora', models.DateField()),
                ('paciente_pac_run', models.IntegerField(null=True)),
                ('atencion_ate_id', models.IntegerField()),
                ('especialidad_esp_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('med_run', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_run', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=15)),
                ('snombre', models.CharField(max_length=15)),
                ('apaterno', models.CharField(max_length=15)),
                ('amaterno', models.CharField(max_length=15)),
                ('telefono', models.IntegerField()),
                ('sueldo_base', models.IntegerField()),
                ('fecha_contrato', models.DateField()),
                ('especialidad_esp_id', models.IntegerField()),
                ('correo_medico', models.CharField(max_length=150)),
                ('contraseña_medico', models.CharField(max_length=50)),
                ('afp_id_afp', models.IntegerField()),
                ('prevision_salud_id_prevision', models.IntegerField()),
                ('descuento_sueldo_id_descuento1', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('pac_run', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_run', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=15)),
                ('snombre', models.CharField(max_length=15)),
                ('apaterno', models.CharField(max_length=15)),
                ('amaterno', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('salud_sal_id', models.IntegerField(null=True)),
                ('correo_paciente', models.CharField(max_length=150)),
                ('contraseña_paciente', models.CharField(max_length=50)),
                ('genero_paciente', models.CharField(max_length=5)),
                ('direccion_id_direccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PagoAtencion',
            fields=[
                ('atencion_ate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('valor_a_pagar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrevisionSalud',
            fields=[
                ('id_prevision', models.IntegerField(primary_key=True, serialize=False)),
                ('prevision', models.CharField(max_length=50)),
                ('descuento_prevision', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Relation14',
            fields=[
                ('hora_id_hora', models.IntegerField(primary_key=True, serialize=False)),
                ('empleado_id_empleado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Relation15',
            fields=[
                ('empleado_id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('pago_atencion_atencion_ate_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumenAtenMedicasMensuales',
            fields=[
                ('mes_anno_atencion', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('total_aten_unid_ambul', models.IntegerField()),
                ('total_aten_unid_urgen', models.IntegerField()),
                ('total_aten_unid_pacritico', models.IntegerField()),
                ('total_aten_unid_adulto', models.IntegerField()),
                ('total_aten_unid_infantil', models.IntegerField()),
                ('total_aten_unid_maternidad', models.IntegerField()),
                ('total_aten_unid_cirugia', models.IntegerField()),
                ('total_aten_unid_cirugia_plast', models.IntegerField()),
                ('total_aten_unid_sobrep_obes', models.IntegerField()),
                ('fecha_grabacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('sal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('costo_pago', models.IntegerField()),
                ('tipo_salud_tipo_sal_id', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSalud',
            fields=[
                ('tipo_sal_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='HorasAtencionMedico',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
