# Generated by Django 4.2.7 on 2023-11-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0008_remove_medico_descuento_sueldo_id_descuento1_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hora',
            table='Hora',
        ),
    ]
