# Generated by Django 4.2.7 on 2023-11-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0010_alter_hora_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medico',
            table='medico',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='paciente',
        ),
    ]
