# Generated by Django 4.2.7 on 2023-11-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0011_alter_medico_table_alter_paciente_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='afp',
            table='afp',
        ),
        migrations.AlterModelTable(
            name='atencion',
            table='atencion',
        ),
        migrations.AlterModelTable(
            name='cargo',
            table='cargo',
        ),
        migrations.AlterModelTable(
            name='centromedico',
            table='centro_medico',
        ),
        migrations.AlterModelTable(
            name='comuna',
            table='comuna',
        ),
        migrations.AlterModelTable(
            name='detalleatenmedicasmensuales',
            table='detalle_atenmedicas_mensuales',
        ),
        migrations.AlterModelTable(
            name='direccion',
            table='direccion',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleado',
        ),
        migrations.AlterModelTable(
            name='erroresproceso',
            table='errores_proceso',
        ),
        migrations.AlterModelTable(
            name='especialidad',
            table='especialidad',
        ),
        migrations.AlterModelTable(
            name='pagoatencion',
            table='pago_atencion',
        ),
        migrations.AlterModelTable(
            name='previsionsalud',
            table='prevision_salud',
        ),
        migrations.AlterModelTable(
            name='relation14',
            table='relation_14',
        ),
        migrations.AlterModelTable(
            name='relation15',
            table='relation_15',
        ),
        migrations.AlterModelTable(
            name='resumenatenmedicasmensuales',
            table='resumen_atenmedicas_mensuales',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='salud',
            table='salud',
        ),
        migrations.AlterModelTable(
            name='tiposalud',
            table='tipo_salud',
        ),
    ]
