# Generated by Django 4.2.7 on 2023-11-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0013_alter_hora_paciente_pac_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='medico_med_run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hora',
            name='paciente_pac_run',
            field=models.IntegerField(null=True),
        ),
    ]
