# Generated by Django 4.2.7 on 2023-11-24 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0015_alter_hora_especialidad_esp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hora',
            old_name='especialidad_esp_id',
            new_name='especialidad_esp_id_id',
        ),
        migrations.RenameField(
            model_name='hora',
            old_name='medico_med_run',
            new_name='medico_med_run_id',
        ),
    ]
