# Generated by Django 4.2.7 on 2023-11-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0016_rename_especialidad_esp_id_hora_especialidad_esp_id_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hora',
            old_name='especialidad_esp_id_id',
            new_name='especialidad_esp_id',
        ),
        migrations.RenameField(
            model_name='hora',
            old_name='paciente_pac_run',
            new_name='paciente_pac_run_id',
        ),
    ]
