# Generated by Django 4.2.7 on 2023-11-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0018_rename_especialidad_esp_id_hora_especialidad_esp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hora',
            name='agendado',
            field=models.BooleanField(default=False),
        ),
    ]
