# Generated by Django 4.2.7 on 2023-11-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0019_hora_agendado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Rut Paciente'},
        ),
    ]
