# Generated by Django 4.2.7 on 2023-12-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0020_alter_paciente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.AlterField(
            model_name='atencion',
            name='centro_medico_id_centro_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centromedico.centromedico'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='hora_id_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.hora'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='medico_med_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.medico'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='pac_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.paciente'),
        ),
        migrations.AlterField(
            model_name='hora',
            name='id_hora',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
