# Generated by Django 4.2.7 on 2023-12-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0021_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='hora',
            name='atencion_ate_id',
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='direccion_id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centromedico.direccion'),
        ),
        migrations.AlterField(
            model_name='detalleatenmedicasmensuales',
            name='atencion_ate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='centromedico.atencion'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='comuna_id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.comuna'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='afp_id_afp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.afp'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='prevision_salud_id_prevision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.previsionsalud'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol_id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.rol'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='afp_id_afp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.afp'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad_esp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.especialidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='prevision_salud_id_prevision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.previsionsalud'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion_id_direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.direccion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='salud_sal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centromedico.salud'),
        ),
        migrations.AlterField(
            model_name='pagoatencion',
            name='atencion_ate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='centromedico.atencion'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='tipo_salud_tipo_sal_id',
            field=models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='centromedico.tiposalud'),
        ),
    ]
