# Generated by Django 4.2.7 on 2023-12-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0022_remove_empleado_rol_remove_hora_atencion_ate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleatenmedicasmensuales',
            name='atencion_ate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='centromedico.atencion', unique=True),
        ),
        migrations.AlterField(
            model_name='pagoatencion',
            name='atencion_ate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='centromedico.atencion', unique=True),
        ),
    ]
