# Generated by Django 4.2.7 on 2023-12-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centromedico', '0023_alter_detalleatenmedicasmensuales_atencion_ate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hora',
            name='costo',
            field=models.IntegerField(null=True),
        ),
    ]
